FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY src/Todo.Service/Todo.Service.csproj src/Todo.Service/
RUN dotnet restore src/Todo.Service/Todo.Service.csproj
COPY src/ src/
WORKDIR /src/src/Todo.Service
RUN dotnet publish -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish ./
ENTRYPOINT ["dotnet", "Todo.Service.dll"]